package com.betcha.model;

import java.util.Date;
import java.util.UUID;

import org.joda.time.DateTime;

import android.content.Context;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;
import com.j256.ormlite.table.DatabaseTable;

/**
 * A bet object we are creating and persisting to the database.
 */

@DatabaseTable(tableName = "bets")
public class Bet extends BaseDaoEnabled  {
	Bet me; //help avoid destruction of object till call back is called
	
	public static final String STATE_OPEN = "open";
	public static final String STATE_DUE = "due";
	public static final String STATE_CLOSED = "closed";

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId  = true)
	private int id;
	@DatabaseField
	private int server_id;
	@DatabaseField(canBeNull = false)
	private String uuid;
	@DatabaseField(canBeNull = false, foreign = true, foreignAutoRefresh = true)
	private User user; //owner
	@DatabaseField
	private String subject;
	@DatabaseField
	private String reward; //benefit
	@DatabaseField
	private DateTime date;
	@DatabaseField
	private DateTime dueDate;
	@DatabaseField
	private String state; // open/due/closed

	public Bet() {
		this.uuid = UUID.randomUUID().toString();
	}

	public Bet(Context context, User owner, String betSubject, String betReward,
			DateTime date, boolean myBet, Date dueDate, String state) {
		super();
	
		this.user = owner;
		this.subject = betSubject;
		this.reward = betReward;
		this.date = date;
		this.uuid = UUID.randomUUID().toString();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getOwner() {
		return user;
	}

	public void setOwner(User owner) {
		this.user = owner;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String betSubject) {
		this.subject = betSubject;
	}

	public String getReward() {
		return reward;
	}

	public void setReward(String betReward) {
		this.reward = betReward;
	}

	public DateTime getDate() {
		return date;
	}

	public void setDate(DateTime date) {
		this.date = date;
	}

	public DateTime getDueDate() {
		return dueDate;
	}

	public void setDueDate(DateTime dueDate) {
		this.dueDate = dueDate;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getServer_id() {
		return server_id;
	}

	public void setServer_id(int server_id) {
		this.server_id = server_id;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
}
