package com.betcha.model;

import org.joda.time.DateTime;

import android.content.Context;

import com.betcha.api.model.RESTUserBet;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "usersbets")
public class UserBet extends BaseDaoEnabled {
	private UserBet me; //help avoid destruction of object till call back is called
	 
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	private int id;
	@DatabaseField
	private int server_id;
	@DatabaseField(canBeNull = false, foreign = true, foreignAutoRefresh = true)
	private User user;
	@DatabaseField(canBeNull = false, foreign = true, foreignAutoRefresh = true)
	private Bet bet;
	@DatabaseField
	private String user_result_bet;
	@DatabaseField
	private DateTime date;
	@DatabaseField
	private Boolean result;
	@DatabaseField
	private String user_ack; // Yes/No/Pending
	
	public UserBet () {
		
	}
	
	public UserBet(Context context, User user, Bet bet, DateTime date, String myBet, String myAck ) {
		super();
		this.user = user;
		this.bet = bet;
		this.date = date;
		this.user_result_bet = myBet;
		this.user_ack = myAck;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public String getMyBet() {
		return user_result_bet;
	}

	public void setMyBet(String myBet) {
		this.user_result_bet = myBet;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Bet getBet() {
		return bet;
	}

	public void setBet(Bet bet) {
		this.bet = bet;
	}

	public DateTime getDate() {
		return date;
	}

	public void setDate(DateTime date) {
		this.date = date;
	}

	public String getMyAck() {
		return user_ack;
	}

	public void setMyAck(String myAck) {
		this.user_ack = myAck;
	}

	public Boolean getResult() {
		return result;
	}

	public void setResult(Boolean result) {
		this.result = result;
	}

	public int getServer_id() {
		return server_id;
	}

	public void setServer_id(int server_id) {
		this.server_id = server_id;
	}
}
