package com.betcha.model;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.web.client.RestClientException;

import com.betcha.BetchaApp;
import com.betcha.model.cache.ModelCache;
import com.betcha.model.server.api.TokenRestClient;
import com.betcha.model.server.api.UserRestClient;
import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "users")
public class User extends ModelCache<User,Integer> {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	private int id;
	@DatabaseField
	private String name;
	@DatabaseField
	private String email;
	@DatabaseField
	private String password;
	@DatabaseField
	private String provider;
	@DatabaseField
	private String uid;
	@DatabaseField
	private String access_token;
	
	//non persistent
	private static UserRestClient userClient;
	private static Dao<User,Integer> dao;
	
	private Boolean isInvitedToBet = false;
	
	public UserRestClient getUserClient() {
		if(userClient==null)
			userClient = new UserRestClient();
		
		return userClient;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String pass) {
		this.password = pass;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}
	
	public String getProvider() {
		return provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public Boolean getIsInvitedToBet() {
		return isInvitedToBet;
	}

	public void setIsInvitedToBet(Boolean isInvitedToBet) {
		this.isInvitedToBet = isInvitedToBet;
	}
	
	/**
	 * static methods that must be implemented by derived class
	 * @return Dao object
	 * @throws SQLException
	 */
	public static Dao<User,Integer> getModelDao() throws SQLException  {
		if(dao==null){
			dao = getDbHelper().getDao(User.class);;
		}
		return dao;
	}
	
	@Override
	public void initDao() {
		try {
			setDao(getModelDao());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Override
	protected Boolean authenticateCreate() {
		return false;
	}

	/** inherited ModelCache methods */
	public int onRestCreate() {
		if(createUserAccount()>0) {
			return createToken();
		}
		
		return 0;
	}
	
	public int createUserAccount() {
		int res = 0;
		JSONObject jsonUser = null;
		
		try {
			res = createOrUpdateLocal();
		} catch (SQLException e1) {
			e1.printStackTrace();
			return 0;
		}
		
		if (provider == "email") {
			jsonUser = getUserClient().create(name, email, password);
		} else if (provider == "facebook") {
			jsonUser = getUserClient().createOAuth(provider, uid, access_token);
		}
		
		setServer_id(jsonUser.optInt("id",-1));
		try {
			res = updateLocal();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return res;
	}
	
	public int createToken() {
			
		TokenRestClient tokenClient = new TokenRestClient();
		String jsonToken = null;
		if (provider == "email") {
			jsonToken = tokenClient.create(email, password);
		} else if (provider == "facebook") {
			jsonToken = tokenClient.createOAuth(provider, uid, access_token);
		}
					
		BetchaApp.setToken(jsonToken);
		
		if(jsonToken==null) {
			return 0;
		} else {
			return 1;
		}
	}

	public int onRestUpdate() {
		Map<String,String> arg = new HashMap<String, String>();
		arg.put("name", name);
		arg.put("email", email);
		arg.put("password", password);
		arg.put("provider", provider);
		arg.put("uid", uid);
		arg.put("access_token", access_token);
		
		getUserClient().update(arg, server_id);
		
		return getServer_id();
	}

	public int onRestDelete() {
		getUserClient().delete(getServer_id());
		return 1;
	}

	public int onRestSync() {
		User user = getAndCreateUser(getServer_id());
			
		if(user==null)
			return 0;
		else
			return 1;
	}
	
	public static User getAndCreateUser(int server_id) {
		User tmpOwner = null;
		try {
			List<User> listUser = null;
			listUser = User.getModelDao().queryForEq("server_id", server_id);
			if(listUser!=null && listUser.size()>0) {
				tmpOwner = listUser.get(0);
			}
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		if(tmpOwner == null) { //then create it
			tmpOwner = new User();
		}
		
		UserRestClient userClient = new UserRestClient();
		JSONObject jsonOwner = null;
		try {
			jsonOwner = userClient.show(server_id);
		} catch (RestClientException e) {
			e.printStackTrace();
			return null;
		}
		if(jsonOwner==null)
			return null;
		
		
		try {
			tmpOwner.setEmail(jsonOwner.getString("email"));
		} catch (JSONException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		try {
			tmpOwner.setName(jsonOwner.getString("full_name"));
		} catch (JSONException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		try {
			tmpOwner.setServer_id(jsonOwner.getInt("id"));
		} catch (JSONException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
		try {
			tmpOwner.createOrUpdateLocal();
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}
		
		return tmpOwner;
	}
	
	public Boolean setJson(JSONObject json) {
		return true;
	}
}
